import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";





const poppins = Poppins(
  {
    weight:["100", "200", "400", "500", "600", "700"],
  }
);

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.className} antialiased`}>
      <body>
        <header className="px-20 py-2">
          <Navbar/>
        </header>
        <main className="px-20 py-2">{children}</main>
        <footer className="px-20 py-2">
          <Footer/>
        </footer>
      </body>
    </html>
  );
}
